theme: jekyll-theme-cayman
title: 4th Workshop on Automated Vehicle Safety
description: Collocated with IEEE Intelligent Transportation Systems Conference (ITSC)
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - workshop_2021.md
  - talks.md

